# custom web-server
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-server-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
        - path: /prod
          pathType: Prefix
          backend:
            service:
              name: web-server-prod
              port:
                number: 8081
        - path: /staging
          pathType: Prefix
          backend:
            service:
              name: web-server-staging
              port:
                number: 8082