# custom web-server
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-server-ingress
  namespace: production
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "prod.web-server.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-server-prod
            port:
              number: 80
  - host: "staging.web-server.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-server-staging
            port:
              number: 80