apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment-prod
  namespace: production
spec:
  selector:
    matchLabels:
      app: web-server-prod
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: web-server-prod
    spec:
      containers:
      - name: nginx
        image: microservice/web-server
        ports:
        - containerPort: 80
          name: web-server-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment-staging
  namespace: staging
spec:
  selector:
    matchLabels:
      app: web-server-staging
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: web-server-staging
    spec:
      containers:
      - name: web-server-staging
        image: microservice/web-server
        ports:
        - containerPort: 82
          name: web-server-staging